### ISSUE TITLE
Winium CodedUI for windows 10 phone:Configuration issues

### ISSUE THREAD

**Issue by SivagamiSakthivel** [2gis/Winium.StoreApps.CodedUi#40]
Hi Team,

I tried winium codedUI for windows 10 real device and face many configuration issue.Please let me know visual studio version and supported tools required for this.

I used VS2015 enterprise edition. Please find the logs below,i tried all possible solutions suggested in already existing issues.

LOGS:
Starting Winium.StoreApps Driver on port 9999

16:42:43 [DEBUG] Waiting for a connection...
16:42:43 [DEBUG] ACCEPTED REQUEST POST /session HTTP/1.1
16:42:43 [INFO] COMMAND newSession
{
  "desiredCapabilities": {
    "app": "D:\\WiniumDemo\\WiniumDemoVersion1\\WiniumDemoVersion1\\src\\main\\java\\TestAppPackage\\TestArm\\TestArm.appx",
    "debugCodedUI": false,
    "locale": "en-US",
    "deviceName": "Device",
    "deviceIpAddress": "localhost"
  }
}
16:42:49 [INFO] Target device: 'Device'
16:42:49 [INFO] CodedUI Test server IP address is localhost
16:42:49 [INFO] Deploying CodedUI test server.
16:42:49 [INFO] Starting CodedUi Test Server using C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe "D:\WiniumDemo\WiniumDemoVersion1\WiniumDemoVersion1\src\main\resources\WiniumCodedUiDriver\Winium.StoreApps.CodedUITestProject.dll" /Settings:"C:\Users\CH248443\AppData\Local\Temp\tmp7E1.tmp" /InIsolation
16:42:55 [DEBUG] VSTEST:
16:42:55 [INFO] f7744780-91e5-4b93-a7d2-8c125f2bd698 was successfully deployed using Microsoft.Phone.Tools.Deploy
16:42:56 [DEBUG] Sending ping request to Test Server
16:42:58 [DEBUG] RESPONSE:
OK: {"sessionId":"AwesomeSession","status":0,"value":{"platformName":"WindowsPhone","app":"D:\\WiniumDemo\\WiniumDemoVersion1\\WiniumDemoVersion1\\src\\main\\java\\TestAppPackage\\TestArm\\TestArm.appx","debugCaptureLogs":false,"debugCodedUI":false,"deviceIpAddress":"localhost","deviceName":"Device","innerPort":9998,"locale":"en-US","pingTimeout":10}}
16:42:58 [DEBUG] Client closed

**Comment by NickAb** [comment]
Please try the latest build from master, I think it might be a known issues that we fixed in https://github.com/2gis/Winium.StoreApps.CodedUi/commit/3bf2bca51c4675f0edad3b5f7639fea637443925

**Comment by didi2391** [comment]
Hi Nick,

I tried the suggested solution and still face issues.Do i need to install Winium.StoreApps.InnerServer in my workspace?
I believe there is some issue with my initial configuration. Request is nor communicated to the Windows 10 Real Device. Any help please?

"Error occurred while trying to send request to inner driver: System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:9998"


LOGS-
09:21:37 [DEBUG] VSTEST: Microsoft (R) Test Execution Command Line Tool Version 14.0.25420.1
09:21:37 [DEBUG] VSTEST: Copyright (c) Microsoft Corporation.  All rights reserved.
09:21:37 [DEBUG] VSTEST:
09:21:37 [DEBUG] VSTEST: Starting test execution, please wait...
09:21:45 [INFO] f7744780-91e5-4b93-a7d2-8c125f2bd698 was successfully deployed using Microsoft.Phone.Tools.Deploy
09:21:46 [DEBUG] Sending ping request to Test Server
09:21:48 [DEBUG] Sending ping request to Test Server
09:21:50 [DEBUG] Sending ping request to Test Server
09:21:52 [DEBUG] Sending ping request to Test Server
09:21:54 [DEBUG] Sending ping request to Test Server
09:21:56 [DEBUG] Sending ping request to Test Server
09:21:58 [DEBUG] Sending ping request to Test Server
09:22:00 [DEBUG] Sending ping request to Test Server
09:22:02 [DEBUG] Sending ping request to Test Server
09:22:04 [DEBUG] Sending ping request to Test Server
09:22:06 [DEBUG] RESPONSE:
OK: {"sessionId":"AwesomeSession","status":33,"value":"Could not connect to Test Server"}

09:22:06 [WARN] Driver does not support multiple sessions!
09:22:06 [INFO] Closing current session AwesomeSession.
09:22:08 [ERROR] Error occurred while trying to send request to inner driver: System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:9998
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at Winium.StoreApps.Driver.Helpers.Requester.CreateWebRequest(String uri, String content, Int32 timeout) in D:\POC_AutoIt\Dinesh's Code\Winium.StoreApps.CodedUITestProject\Winium.StoreApps.CodedUITestProject\Winium.StoreApps.Driver\Helpers\Requester.cs:line 139
   at Winium.StoreApps.Driver.Helpers.Requester.SendRequest(String requestContent, Boolean verbose, Int32 timeout) in D:\POC_AutoIt\Dinesh's Code\Winium.StoreApps.CodedUITestProject\Winium.StoreApps.CodedUITestProject\Winium.StoreApps.Driver\Helpers\Requester.cs:line 65
09:22:08 [DEBUG] Closing vstest.console

**Comment by SivagamiSakthivel** [comment]
@NickAb This issue is due to firewall that blocks response from port.Please close this ticket

**Comment by NickAb** [comment]
@skyline-gleb could you please close this issue. I don't have rights to do so anymore
